name: gym_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  supabase_flutter: ^2.5.6
  image: ^4.8.0
  mime: ^2.0.0
  path: ^1.9.1
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  screenshot: ^3.0.0
  http: ^1.2.0
  url_launcher: ^6.3.2
  mobile_scanner: ^3.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/success.mp3
    - assets/error.mp3